name: 'Comment Test Coverage'
description: 'Read a Test Coverage json-summary test report and add stats on to PR using a table that rewrites itself on successive pushes'
inputs:
  token:
    description: 'The GitHub authentication token'
    required: true
  path:
    description: 'Filepath to json-summary file'
    required: true
  title:
    description: 'Comment title in PR conversation'
    required: false
    default: 'Test Coverage'
  id:
    description: 'Unique identifier for this comment. Specify a different value for each project in a monorepo.'
    required: false
    default: 'comment-test-coverage-1'
  issue_number:
    description: 'Issue number. Used if provided, to work outside pull_request events.'
    required: false
    default: ''
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'message-square'
  color: 'gray-dark'
