name: run-coverage

on: [pull_request]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - run: npm install
    - run: npm run package

    - uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        path: test/_stubs/coverage-summary-100-pct.json
        title: Test Coverage - Stub 100 pct
        id: project-1
    
    - uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        path: test/_stubs/coverage-summary-90-pct.json
        title: Test Coverage - Stub 90 pct
        id: project-2

    - uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        path: test/(?<app>app[^/]+)/coverage-summary-90-pct.json
        title: Test Coverage - ${app}
        id: ${app}
    
